env:
  global:
    - VERSION=v0.1
    - FLASK_APP=app
    - FLASK_ENV=development
    - secure:

services:
- docker

script:
- docker build --target production --tag todo-app:$VERSION .

script:
- docker build --target test --tag todo-app-test:$VERSION .
