env:
  global:
  - VERSION=v0.1
  - FLASK_APP=app
  - FLASK_ENV=development
  - MONGO_DEFAULT_DATABASE=todoBoard
  - DOCKER_NAMESPACE=pcoulso1
  - DOCKER_APP=todo-app
  - OAUTHLIB_INSECURE_TRANSPORT=1
  - GITHUB_LOGON_REDIRECT=http://localhost:5000/login/callback
  - AZURE_GITHUB_LOGON_REDIRECT=https://dev-todo-pcoulson.azurewebsites.net/login/callback
  - ARM_CLIENT_ID=41ae24d1-6b3e-448d-92c1-dc3cde25ee47
  - ARM_TENANT_ID=7d6f97d6-d755-4c10-b763-409cc4b6638f
  - ARM_SUBSCRIPTION_ID=d33b95c7-af3c-4247-9661-aa96d47fccc0
  - TF_VERSION=0.14.7
  # Secret for ARM_CLIENT_SECRET
  - secure: iN8JnZW+B4dor+/eJx0MVOR1ITDP9sHr3qGVEyGHgD94FcA7kQtGyzROAzKBjPBvlGRSjzYwuHzz61sMpsm65A10y7MSd066RuG7AIcwVdNuyOcy1N05SzVz/vl3dH6ePrFNvErW+/YWranaaVkQiCMm+RNdPDvbC2hepqwYz6uUeBqboG2kTgDtu7IDdBdiYdulgVkZOeS1MhlT3PVsa/udChC4oFVM9qVBNxHFMs8MffBCw8BYHOPBA9D+d0CO1nf6DVQ1/EIj+88hm9gusj2N+i5yzPScLR9gtKM+2DtJeUTUosrir2jqQRjdDnI+ZcuEUjxeLrZ47cISd+14cFTcrLOrkDJs4yr07QN5sWEGCPUDYwriWHZHg99Duw6EQu9moJaTDXFNtfbslV6KDRK0NhqLwyB9XCi822rc9DgHDyyAvZbQHfryohwR7jvad0wyb6c/yP2YePcFmQNELPj6WryZc8xq2db9ZrbBqZbdhMPYMHqO68HRbLK3LX9XIx4JOliY9cUbetM8wcIZKrGoo+bB77aSHV+lLfLAsCs7YNqTgwr2zyy9a9rEgZF8T8DYZgG+qjnU7h5x7DX8xSWwCnOosINd20dsZ+fF+a/Da5wqbCnDOoj6BlBRW3j4a3hdoWDlPeXReeh2zkyMwH5jp0jvF6ZoyPd5P2GmFIM=
  # Secret for MONGO_URL (needed to run it through bash printf %q "MONGO_URL=<var>" to escape the string)
  - secure: jckb3YGnrKxlJxlgy9gYmU7JbkMi7dCQUZM3m2qwV61MI4ntUiAt8fMTAhCCQthSIWWe9PEa0EKBnBHJ8CJHD4f9fLv8lV/2f2u6KlP9djizXNKknz7GHrNJIWiqdmC6GxHpt/3D7imd20EwBTi9spwS1UFiogDGtqN6SUk4IPRxEVhGH+9WdpX3uFgOLa+xtzA7eNXr4fQnPGapvnSBbNgN05XH/mb1wUeLFX0/5fLbnL+K95YyPyjJci145YxlHept5MvJ7tWt9qtqyDsl2eEvQiR56PeoIwM8CbNnOWrL/LfK3RpRyuLSPIKEuzHqwhvL4llp8NIRAexZ18xN/oBRhabD9vEI7tv87LNhIj6wsaHnPATfcec8Wb3ER90fsin5GMrcuPtHxmCmGE59WS96tau1gsmsIotUieqHD8UHRV5EUFObYwmwXOE2t39+JA5aO3ydzCOklUAa0QV1D8lR7NrJPTztKRLKq2uNmk035IlhMtNiTjRkT2vA4GDchdihDJQ1SqTL3aAVeHRL3gdMNZ2O3cCy/6t8N9HgBKi1/E2Stk6nRzPnqcQB0uU+ohS2dr03SoShK+x947vB1YL+L8im7AFJkIpnLeOdxNtXhQ0NRAF0wjhSAvoF8r29uT1FpnCvMTpOZzMrJLrbzcy7w7Jp/55BrB5fThFPZ/Q=
  # Secret for DOCKERHUB_PWD
  - secure: v5mGm2scI7wdxvDfJl9KKs+3JImErlOGntK7fz1fO5EK/PAhFC8KXa4M43zNhnt075JCAufLPPiT6wBfwwgM4QL3YEAvxzD02I1x6RrGr3U8yAwZbrmg7aLC2pSxEuCTZAjxkaGcMOXOTlMqMxBRPsqTcN2gSgKzsdGMSh+pmZ7wOKZAQWh56QkLUmCZ4QbNVeiPS5nMy1guQYADN/fGDMg7c3Q9FLmp4dV8hFFru0RXiIPneVK+Y9vFWPgNGVlgCwIbzZ5yZzcILOz/dMIS/wWDM+hUt0WSd9Px7xsYOvu9xAh7hRLSM/QfJa3XafmmrshrhxZYNwxa7ZjcsJYRYR1e//TbNooxiBqeV7wIdtoJJXvAwA0D69RN/3ek42Cs824bpwi5/erTwNLA6k1nutrAQ00epWYdKH1W5JHeX/ASgV4rRyIkNlmBbQbYApIKPBaJ+l+1iza46V0Lj3zkvyR5Y+lEieeTihd8MLIdWQvWReQtvAArUXgmZqeIHtJDq8HapO9dpkOlREjwha8h4/h8KMJ8AH9KU0ArbvCDq1Lz9GJCoj9+Lp/SvcS2AtRPFTzX1PHDeYWo02vh5UjLv6l9bp2Ot322qb67HLYXqqILZ53Ul4YRt4XFliiHoVxvbnEsCcmhVyDTz6S15wK+JS+mwRF2TbAPWAuj10zRXbA=
  # Secret for GITHUB_CLIENT_ID
  - secure: OM9sL49H8QFIiCzYGXw8LzpdsrF/eX8yi4Xt5YDTDTiRqLcxNbKzztb1fP/+mgcpjkbihpoqG1rBIxLugtQU+hnsStdcwCJLdtq5mI58saLFwzTCz6Cr8v28dJ4E7lTh9EzU5pxR4NPuSlSX+1qnjgh6nxpd8W9afPfGJ5+hJyqR1kVD+GZJX6mTzxTN20FZnAbujL7euObY+mziPDD3BKAruWKNuMftyG5F2vCci74clMg5DxRH1ns1LzuIuKh7Upqwz+AsNcSFq9QmotbD3IDyi5oeT7Bg8mZuev/oQipBtLLl/5moGaJ1dUbMq9k1pRvst5l70M3PaWuIGDszO544SKhSQeR+47Hci/4IP9NGLwx0GeXmeNFvDObvhEZy11hsYkUYL9I2TYeEXH3mC5TRumfrAs5ZvBw7vl/kH+bDn5Dyb+srg6lLT0sbwUmUVlSxgx3LplAAwyH1MhB5FaoeRFtYwo9UR9KEPbRK18Vdpfl11cbpdFKhGtLKxsWdhiW+f4/k1svULQACqeCwSMxL9mkN8ikT7/ZszNAChnfsRrpuW0a+QpSBsHa6gjU6dSpRtjX7/rjtS8lGT898DU+p4A7MdRvDrg3aMxpCN+Uh92+lb6VV3pSgi+zgDux1WW/Q9QCnQJRqyIxmBXf8kalsprxM8umgHbwN1/76Aac=
  # Secret for GITHUB_CLIENT_SECRET
  - secure: utWwfJUI966NqcDec2AccTD8m+m0hVOtVSGGecl2/WRYuwZNAXvROPP5nWjl6ITT/uwGnXm8bVdAM/2W0qSpwzbx2Fc0CveOQEBudxT+rrK3cIiex8ajaLqxXRfke7Rm6uFmUQ+T9Gg8y2SBRto0tuJTN1Ph55EFUBQmcw62NCXBdc48nCgYeoZpYJ1SK5rPBkKf+UAw0q5w1Ltnq4IkRwjF9I5UYLMBf44vfbopZNO2zkMPlFqhZCwozToJ50ouRwiX5uwfazIvOCk34G5V4gcljn+FKOqMtrp05a3pJHRqiZ38HzFedZlicFMO5fbsYqovrq6cbTIuHQzXYaKMRlcr06CL0fQUsGLVIaHOuoKTzUw8Mk6E/wT04ks+yiGigbG3RgXOnsN7bg7bdwVCP50yIpfvCKIf85UaLho8wT9FBXwvkn8bEMxBIg+mkdRh++ANLlWcdof9sAF0bAUjWEK3tgAFJSTnwldsjA4WlYLGOf9uUU1bg84JbQshis92FMQ6U5rAtLPvJnHA/DbrVGx6NCbSUbsGz9FOx2Rtpa7iKsGUgc8reD9RyXoYm/wv2tqQb5Cz8jQ1PEgCsrGE5OIe4q3x3qzxeEijVwEKwfUH6EJ1q0CsTGR/5R2ONuMQD41iT8r3P1eLuw9fv2LRO7beHcF7fjGS/FzYJ52tvK0=
  # Secret for AZURE_GITHUB_CLIENT_ID
  - secure: iM5+B5fsyRZUPrcu0nX7vkEDBJn5J7evqHNHGNwMvOtkN8yudgPIPpgdRJrkdGKvxW3csrH5igV7G+OjUjdSRUVZFLp8Y0DXzSNvO08XDDDO5gnhyPCI4COKxKbAcZape7ujbhkSqUEtNM5GaZNmPeejKY9atB/JX/afaXDB8ZBqq/fPN4n5RxHirDBU3M0vxM5fhaQd7FWnlUmq4lxw/XH0qZKv5QDe86QrSxv+dP3ztCAge/r/URuzreq5yY0cQ/BarI9DGOyyxxdjnBn6IeRz/N0G0+n5pqtYTeL2xfPI7qnslFICFxWUxGRBYSoqebE5VzSSnsiD2ugJGAOA3WjPboF78bLjjYgEfKtVX29qp0peG90FxnVrKv0dkntKv3nlSeRYqB26KM+354tNGt0YnDcWHMkRAtCs29Mh8qizb9A+3QHaKAakxL2k5U2pPASB3Ns1zO63DmAdkpE2j5O0s1IMUROf906wCFmZWjfGj0+9tmfDtLIt5Zu/tyS1YD1JYHqO1M4UM+Zct9tDDhQS74uLZ9OB2hXEcBF8XT+gem/xugSHSrSGu74eX7ni1AoXl6P5Gurw12gW05+WU/u3YYKDFpKy1EWRNy/EiOOAA+41P0bHTkOdlOrh4vDC4ntj3nLGWfPdrwx47w3MEJTOiImr+F6rGCThz+wxAKo=
  # Secret for AZURE_GITHUB_CLIENT_SECRET
  - secure: 4HjHH0XHV0El5P7Dk8DKb+aS2uzQZhfuRkmiMMMtbJsqnPJ2I8CTRLwLKLqp9TiMONpMcyKvERyi8PwNHFMCeGJKwyfOVBdl7+nWIcHS+9ejkYmd1/VpDNHAE6BxWvLjiTiCV3VzunQOlZvrYc5RE5LUJdQ4+TMwZ6e4uPozTBQeY2hCjUzNCn7K1L4/rNK5dniNB7VtNQIewm5vGcKqiSG4tlp78+GopBobBfRE7V83pmRcqpHGyKQaTYzhae05CVyVh28XQBgNh003dDbj1loYdHxAA7BlJJPeoD9VA3c1bxsI+/dHbh9LEr7pCoVjf9WXgSobPRmY1ZZJSp9twdD0OARK0GrQk2r9xowXMjVyW0rB5+QxdCK2/BNlAFdbtIGDURVfx98FTYTp0G8woHjlMyTQlDrBiV0eAYs6tqKsRGXzzHZrMtr5ZFXXh/3zJ6/hnUM5E5mGnL5GGui5UFPXmib4j5KDOBNVOLI51omuHE/htuVuqdwtS1thwoVZekQq2Oz7yvCC0w0T/WpNHhmcuKPeQvodVSoXiOPnbvBVyQkF4TPsn/maZzjAhXrfe5VduS7wPI/ergEm3jyVhoD9F84/Nq5iIMYlSMaO1N8uG5XzmDY+7Ip7WG5RM+AgUvWmvAdgbYanarZiKrdnV6MB2N4f42/SBiqRUTHOt+k=

services:
  - docker

script:
  - docker info
  # - docker build --target production --tag $DOCKER_NAMESPACE/$DOCKER_APP .
  # - docker tag $DOCKER_NAMESPACE/$DOCKER_APP $DOCKER_NAMESPACE/$DOCKER_APP:$TRAVIS_COMMIT
  # - docker build --target test --tag $DOCKER_NAMESPACE/$DOCKER_APP-test .
  # - docker run --rm -e FLASK_APP -e FLASK_ENV -e MONGO_URL -e MONGO_DEFAULT_DATABASE -e OAUTHLIB_INSECURE_TRANSPORT -e GITHUB_CLIENT_ID -e GITHUB_CLIENT_SECRET -e GITHUB_LOGON_REDIRECT $DOCKER_NAMESPACE/$DOCKER_APP-test tests
  # - docker run --rm -e FLASK_APP -e FLASK_ENV -e MONGO_URL -e MONGO_DEFAULT_DATABASE -e OAUTHLIB_INSECURE_TRANSPORT -e GITHUB_CLIENT_ID -e GITHUB_CLIENT_SECRET -e GITHUB_LOGON_REDIRECT $DOCKER_NAMESPACE/$DOCKER_APP-test tests_e2e

before_deploy:
  - echo $DOCKERHUB_PWD | docker login --username $DOCKER_NAMESPACE --password-stdin
  # - docker push $DOCKER_NAMESPACE/$DOCKER_APP:$TRAVIS_COMMIT
  # docker push $DOCKER_NAMESPACE/$DOCKER_APP && 

deploy:
  - provider: script
    script: >-
      wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip && 
      unzip terraform_"$TF_VERSION"_linux_amd64.zip && 
      sudo mv terraform /usr/local/bin/ && 
      rm terraform_"$TF_VERSION"_linux_amd64.zip && 
      terraform init && 
      terraform apply -auto-approve -var "github_client_id=$AZURE_GITHUB_CLIENT_ID" -var "github_client_secret=$AZURE_GITHUB_CLIENT_SECRET" -var "github_logon_redirect=$AZURE_GITHUB_LOGON_REDIRECT" && 
      export AZURE_WEBHOOK="$(printf %q $(terraform output -raw cd_webhook))" &&
      echo curl -dH -X POST "$AZURE_WEBHOOK" &&
      exit 0;

    on:
      branch: module-12

branches:
  only:
  - module-12
    
notifications:
  email:
    recipients:
    - pcoulson@btinternet.com
    on_success: change
    on_failure: always
