env:
  global:
  - VERSION=v0.1
  - FLASK_APP=app
  - FLASK_ENV=development
  - MONGO_HOST=cluster0.xrdya.mongodb.net
  - MONGO_DEFAULT_DATABASE=todoBoard
  - DOCKER_NAMESPACE=pcoulso1
  - DOCKER_APP=todo-app
  - HEROKU_APP=dev-ops-todo-app
  # Secret for MONGO_USER_NAME
  - secure: DKbvOtyZbv6CjTEPScNJ+yOG5EQh27+uZuiqu8Rns4nyqaY5dX+zS6Lq27UowsjI0/j3qJdIgKo5/c45KUzWUfTdEYlaAlG2QzZ5x3e+WjRHk20ZX5zPRFdxG7mmIFsK72DdF5vKVigES3Owcgofu0S8JcpJpZA7CRe3ijtCzMl0ylPNpoqTyKTEusBLqlpACzGf45DoRvPuvqDZh1CnGv572ODpoSvh/s3a9+M9rTRRO+9pAYI0ArjKfTSg67HHTHzap9CD2WNtn7xusiN48X6l9zgRMEO4hJ+62AaJa8A2FGABcDr/IXwcpVze6970BSJlUu4HoFHITwLwLAMvQWKqbsBkgzpbrWhY/x+RFJdM5tS2dztuateQu2JGkdZiFYsriY4nccOzThSiXHx+vV0vEMxoiHAbR1CUJuFelHCbZE4SNI/pfqM+qiAnwMvhTeGuQMgonf5l2qTT6P7YIYXCF2IfOVnOLmuCrcSxREb2t3dF3rvfbHKGbwXJckzpisp+o02CE0dL0JYyGeQrPYqlpbMA2JeGJNGCz4NQDKXHj4+o8o16nImvhAWFcGvHdiEZBi92j86A3osI8VUCsFv+znKaVgZYUQsd4ZKumoTSvVltqD+z6w9291pWi0Huy1mEB8wFZSzJ8sCnuM+7PtJHh50+OkebWzHp/zQysWo=
  # Secret for MONGO_PASSWORD
  - secure: WGKEUj29mPVqbrF/EZA/ZYCJ0r7QinMuFAjYXrhX2XhLfnPuvSyEJirz0UeBfo44g0oucJ5RTJG2elSzXiFTZtKhsvqLWesflJdD+pgF8S6AabN3yugiYR5TAgMrY1WDRlAoo2RHMLM8clQqeOSJJ1XOlhqraxLY0LZzmgk+RUJEh11PBWz+kNg5mhylTAPH9sOHWrUCNJIdDyd0znqTLGYTlQo7trj+wTSC5lIDqa8ksXzMxabIYwHX6QylcGgsUQupdEb1bXYxbUriqZa5ezFllF0IpbmejPfL8d4F7g1rBRE0SQhaK6EXbSePzy4d+3zmdYjBQWLbAKt8Ep7mvF+sLlvrZ0/QYkUdJcVp8Wb2AD59b6u+FPJZSDZqyYFAKv+3ASz5kVrdtmChd3bNYHKaUhx2z71l2Ow+ffHBWh+/Dxq4Qw3pdjjvhiwYjpABfDLAItKhbPGN5NFd8ESurahe934aP3qdBw/1dwwfoWXP9MNeWrEsmTrswIxBLIOSQk9LgpoEvUI+OKwOz25VJ6XCKd9AIOA+9A4m0ynMcO7Lyakdtoi/PU8Aljsu2FuVDmitWHDZYlMQrPS5ZtwzC1DSbaiPQJ6BEj/gUtMweFHZh/4KH1UaiKwUFtsJIuUOU4hPu4KuQ3Pr3T0937gcFb+RMGek5XnrYWKZK5EIFYQ=
  # Secret for DOCKERHUB_PWD
  - secure: v5mGm2scI7wdxvDfJl9KKs+3JImErlOGntK7fz1fO5EK/PAhFC8KXa4M43zNhnt075JCAufLPPiT6wBfwwgM4QL3YEAvxzD02I1x6RrGr3U8yAwZbrmg7aLC2pSxEuCTZAjxkaGcMOXOTlMqMxBRPsqTcN2gSgKzsdGMSh+pmZ7wOKZAQWh56QkLUmCZ4QbNVeiPS5nMy1guQYADN/fGDMg7c3Q9FLmp4dV8hFFru0RXiIPneVK+Y9vFWPgNGVlgCwIbzZ5yZzcILOz/dMIS/wWDM+hUt0WSd9Px7xsYOvu9xAh7hRLSM/QfJa3XafmmrshrhxZYNwxa7ZjcsJYRYR1e//TbNooxiBqeV7wIdtoJJXvAwA0D69RN/3ek42Cs824bpwi5/erTwNLA6k1nutrAQ00epWYdKH1W5JHeX/ASgV4rRyIkNlmBbQbYApIKPBaJ+l+1iza46V0Lj3zkvyR5Y+lEieeTihd8MLIdWQvWReQtvAArUXgmZqeIHtJDq8HapO9dpkOlREjwha8h4/h8KMJ8AH9KU0ArbvCDq1Lz9GJCoj9+Lp/SvcS2AtRPFTzX1PHDeYWo02vh5UjLv6l9bp2Ot322qb67HLYXqqILZ53Ul4YRt4XFliiHoVxvbnEsCcmhVyDTz6S15wK+JS+mwRF2TbAPWAuj10zRXbA=
  # Secret for HEROKU_API_KEY
  - secure: ntNKVgg8INALzPNi+wkmanRFGTNrCQzPfVycmWbe1Pls3jQEC98Z6lhUcBpxY/+vsv0ZyKmYH06MTvpcOgKxFY3wdq5MliMcOWKyYoZWPK2M/9MzuNZxkDKvJNhhc8oxbkB3zJCpDWf6dm7nucIZ5OcJjOu4WrLspdsjERIrgODGZu3/ico7VM0q3jQPjdyogsgvRSJ+MqfcJeNJpJi0dUCmIVT368BKJlgS7cf2jFZtwwNcNskMeV3Ej8p1Iq5DWfPcyGe84ejhG+J2s8sCkobD/dMmoGIrSnvtx3ACI4Nu/WuGjB4gJyl4T8ElVCgkIy5Dn4tEzCc/fMhaJKoveyNw+cUEevCDcGEw2+eVegymLAwUV1sr/N1NtWG8/ucgxjn2wRKrsLKKb7sKvjaKP2fzl2LVEo1GvsbykHbwlqjjFPLVTXMYr3GCq/X7UcUH8uxEo7gOD6bTdAP/YtOC18q1by+vy/+zAOW0/RgjbjOJQLfrBH5Q4fVquN59uotNO+Bc22iyCtO226ViKlNaPC+X9xDS0OV6GfARlKRhKKUvIDLi3l7oMBuzKr6cQBMf7oyDdr0KQUbpFXYpAiikkXFp8wMtks7WNg28HjWdHaQIoeQqyaTqptZwv2B9NNc67x2jQtRl3asr246RTGRCjJ2z6Z5Oc4eOBTKHyVybZbU=

services:
- docker

script:
- docker build --target production --tag $DOCKER_NAMESPACE/$DOCKER_APP .
- docker tag $DOCKER_NAMESPACE/$DOCKER_APP $DOCKER_NAMESPACE/$DOCKER_APP:$TRAVIS_COMMIT
- docker build --target test --tag $DOCKER_NAMESPACE/$DOCKER_APP-test .
- docker run --rm -e FLASK_APP -e FLASK_ENV -e MONGO_HOST -e MONGO_USER_NAME -e MONGO_PASSWORD -e MONGO_DEFAULT_DATABASE $DOCKER_NAMESPACE/$DOCKER_APP-test tests
- docker run --rm -e FLASK_APP -e FLASK_ENV -e MONGO_HOST -e MONGO_USER_NAME -e MONGO_PASSWORD -e MONGO_DEFAULT_DATABASE $DOCKER_NAMESPACE/$DOCKER_APP-test tests_e2e
- echo $DOCKERHUB_PWD | docker login --username $DOCKER_NAMESPACE --password-stdin
- docker push $DOCKER_NAMESPACE/$DOCKER_APP:$TRAVIS_COMMIT
- if [ "$TRAVIS_BRANCH" = "master" ]; then docker push $DOCKER_NAMESPACE/$DOCKER_APP; fi

deploy:
  - provider: script
    script: 
      echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com &&
      docker tag $DOCKER_NAMESPACE/$DOCKER_APP:$TRAVIS_COMMIT registry.heroku.com/$HEROKU_APP/web &&
      docker push registry.heroku.com/$HEROKU_APP/web &&
      wget -qO- https://cli-assets.heroku.com/install.sh | sh &&
      /usr/local/bin/heroku container:release --app dev-ops-todo-app web


branches:
  only:
  - master

notifications:
  email:
    recipients:
    - pcoulson@btinternet.com
    on_success: change
    on_failure: always
