env:
  global:
  - VERSION=v0.1
  - FLASK_APP=app
  - FLASK_ENV=development
  - MONGO_DEFAULT_DATABASE=todoBoard
  - DOCKER_NAMESPACE=pcoulso1
  - DOCKER_APP=todo-app
  - HEROKU_APP=dev-ops-todo-app
  - OAUTHLIB_INSECURE_TRANSPORT=1
  - GITHUB_LOGON_REDIRECT=http://localhost:5000/login/callback
  # Secret for MONGO_URL (needed to run it through bash printf %q "MONGO_URL=<var>" to escape the string)
  - secure: jckb3YGnrKxlJxlgy9gYmU7JbkMi7dCQUZM3m2qwV61MI4ntUiAt8fMTAhCCQthSIWWe9PEa0EKBnBHJ8CJHD4f9fLv8lV/2f2u6KlP9djizXNKknz7GHrNJIWiqdmC6GxHpt/3D7imd20EwBTi9spwS1UFiogDGtqN6SUk4IPRxEVhGH+9WdpX3uFgOLa+xtzA7eNXr4fQnPGapvnSBbNgN05XH/mb1wUeLFX0/5fLbnL+K95YyPyjJci145YxlHept5MvJ7tWt9qtqyDsl2eEvQiR56PeoIwM8CbNnOWrL/LfK3RpRyuLSPIKEuzHqwhvL4llp8NIRAexZ18xN/oBRhabD9vEI7tv87LNhIj6wsaHnPATfcec8Wb3ER90fsin5GMrcuPtHxmCmGE59WS96tau1gsmsIotUieqHD8UHRV5EUFObYwmwXOE2t39+JA5aO3ydzCOklUAa0QV1D8lR7NrJPTztKRLKq2uNmk035IlhMtNiTjRkT2vA4GDchdihDJQ1SqTL3aAVeHRL3gdMNZ2O3cCy/6t8N9HgBKi1/E2Stk6nRzPnqcQB0uU+ohS2dr03SoShK+x947vB1YL+L8im7AFJkIpnLeOdxNtXhQ0NRAF0wjhSAvoF8r29uT1FpnCvMTpOZzMrJLrbzcy7w7Jp/55BrB5fThFPZ/Q=
  # Secret for DOCKERHUB_PWD
  - secure: v5mGm2scI7wdxvDfJl9KKs+3JImErlOGntK7fz1fO5EK/PAhFC8KXa4M43zNhnt075JCAufLPPiT6wBfwwgM4QL3YEAvxzD02I1x6RrGr3U8yAwZbrmg7aLC2pSxEuCTZAjxkaGcMOXOTlMqMxBRPsqTcN2gSgKzsdGMSh+pmZ7wOKZAQWh56QkLUmCZ4QbNVeiPS5nMy1guQYADN/fGDMg7c3Q9FLmp4dV8hFFru0RXiIPneVK+Y9vFWPgNGVlgCwIbzZ5yZzcILOz/dMIS/wWDM+hUt0WSd9Px7xsYOvu9xAh7hRLSM/QfJa3XafmmrshrhxZYNwxa7ZjcsJYRYR1e//TbNooxiBqeV7wIdtoJJXvAwA0D69RN/3ek42Cs824bpwi5/erTwNLA6k1nutrAQ00epWYdKH1W5JHeX/ASgV4rRyIkNlmBbQbYApIKPBaJ+l+1iza46V0Lj3zkvyR5Y+lEieeTihd8MLIdWQvWReQtvAArUXgmZqeIHtJDq8HapO9dpkOlREjwha8h4/h8KMJ8AH9KU0ArbvCDq1Lz9GJCoj9+Lp/SvcS2AtRPFTzX1PHDeYWo02vh5UjLv6l9bp2Ot322qb67HLYXqqILZ53Ul4YRt4XFliiHoVxvbnEsCcmhVyDTz6S15wK+JS+mwRF2TbAPWAuj10zRXbA=
  # Secret for HEROKU_API_KEY
  - secure: ntNKVgg8INALzPNi+wkmanRFGTNrCQzPfVycmWbe1Pls3jQEC98Z6lhUcBpxY/+vsv0ZyKmYH06MTvpcOgKxFY3wdq5MliMcOWKyYoZWPK2M/9MzuNZxkDKvJNhhc8oxbkB3zJCpDWf6dm7nucIZ5OcJjOu4WrLspdsjERIrgODGZu3/ico7VM0q3jQPjdyogsgvRSJ+MqfcJeNJpJi0dUCmIVT368BKJlgS7cf2jFZtwwNcNskMeV3Ej8p1Iq5DWfPcyGe84ejhG+J2s8sCkobD/dMmoGIrSnvtx3ACI4Nu/WuGjB4gJyl4T8ElVCgkIy5Dn4tEzCc/fMhaJKoveyNw+cUEevCDcGEw2+eVegymLAwUV1sr/N1NtWG8/ucgxjn2wRKrsLKKb7sKvjaKP2fzl2LVEo1GvsbykHbwlqjjFPLVTXMYr3GCq/X7UcUH8uxEo7gOD6bTdAP/YtOC18q1by+vy/+zAOW0/RgjbjOJQLfrBH5Q4fVquN59uotNO+Bc22iyCtO226ViKlNaPC+X9xDS0OV6GfARlKRhKKUvIDLi3l7oMBuzKr6cQBMf7oyDdr0KQUbpFXYpAiikkXFp8wMtks7WNg28HjWdHaQIoeQqyaTqptZwv2B9NNc67x2jQtRl3asr246RTGRCjJ2z6Z5Oc4eOBTKHyVybZbU=
  # Secret for GITHUB_CLIENT_ID
  - secure: OM9sL49H8QFIiCzYGXw8LzpdsrF/eX8yi4Xt5YDTDTiRqLcxNbKzztb1fP/+mgcpjkbihpoqG1rBIxLugtQU+hnsStdcwCJLdtq5mI58saLFwzTCz6Cr8v28dJ4E7lTh9EzU5pxR4NPuSlSX+1qnjgh6nxpd8W9afPfGJ5+hJyqR1kVD+GZJX6mTzxTN20FZnAbujL7euObY+mziPDD3BKAruWKNuMftyG5F2vCci74clMg5DxRH1ns1LzuIuKh7Upqwz+AsNcSFq9QmotbD3IDyi5oeT7Bg8mZuev/oQipBtLLl/5moGaJ1dUbMq9k1pRvst5l70M3PaWuIGDszO544SKhSQeR+47Hci/4IP9NGLwx0GeXmeNFvDObvhEZy11hsYkUYL9I2TYeEXH3mC5TRumfrAs5ZvBw7vl/kH+bDn5Dyb+srg6lLT0sbwUmUVlSxgx3LplAAwyH1MhB5FaoeRFtYwo9UR9KEPbRK18Vdpfl11cbpdFKhGtLKxsWdhiW+f4/k1svULQACqeCwSMxL9mkN8ikT7/ZszNAChnfsRrpuW0a+QpSBsHa6gjU6dSpRtjX7/rjtS8lGT898DU+p4A7MdRvDrg3aMxpCN+Uh92+lb6VV3pSgi+zgDux1WW/Q9QCnQJRqyIxmBXf8kalsprxM8umgHbwN1/76Aac=
  # Secret for GITHUB_CLIENT_SECRET
  - secure: utWwfJUI966NqcDec2AccTD8m+m0hVOtVSGGecl2/WRYuwZNAXvROPP5nWjl6ITT/uwGnXm8bVdAM/2W0qSpwzbx2Fc0CveOQEBudxT+rrK3cIiex8ajaLqxXRfke7Rm6uFmUQ+T9Gg8y2SBRto0tuJTN1Ph55EFUBQmcw62NCXBdc48nCgYeoZpYJ1SK5rPBkKf+UAw0q5w1Ltnq4IkRwjF9I5UYLMBf44vfbopZNO2zkMPlFqhZCwozToJ50ouRwiX5uwfazIvOCk34G5V4gcljn+FKOqMtrp05a3pJHRqiZ38HzFedZlicFMO5fbsYqovrq6cbTIuHQzXYaKMRlcr06CL0fQUsGLVIaHOuoKTzUw8Mk6E/wT04ks+yiGigbG3RgXOnsN7bg7bdwVCP50yIpfvCKIf85UaLho8wT9FBXwvkn8bEMxBIg+mkdRh++ANLlWcdof9sAF0bAUjWEK3tgAFJSTnwldsjA4WlYLGOf9uUU1bg84JbQshis92FMQ6U5rAtLPvJnHA/DbrVGx6NCbSUbsGz9FOx2Rtpa7iKsGUgc8reD9RyXoYm/wv2tqQb5Cz8jQ1PEgCsrGE5OIe4q3x3qzxeEijVwEKwfUH6EJ1q0CsTGR/5R2ONuMQD41iT8r3P1eLuw9fv2LRO7beHcF7fjGS/FzYJ52tvK0=

services:
- docker

script:
- docker build --target production --tag $DOCKER_NAMESPACE/$DOCKER_APP .
- docker tag $DOCKER_NAMESPACE/$DOCKER_APP $DOCKER_NAMESPACE/$DOCKER_APP:$TRAVIS_COMMIT
- docker build --target test --tag $DOCKER_NAMESPACE/$DOCKER_APP-test .
- docker run --rm -e FLASK_APP -e FLASK_ENV -e MONGO_URL -e MONGO_DEFAULT_DATABASE -e OAUTHLIB_INSECURE_TRANSPORT -e GITHUB_CLIENT_ID -e GITHUB_CLIENT_SECRET -e GITHUB_LOGON_REDIRECT $DOCKER_NAMESPACE/$DOCKER_APP-test tests
- docker run --rm -e FLASK_APP -e FLASK_ENV -e MONGO_URL -e MONGO_DEFAULT_DATABASE -e OAUTHLIB_INSECURE_TRANSPORT -e GITHUB_CLIENT_ID -e GITHUB_CLIENT_SECRET -e GITHUB_LOGON_REDIRECT $DOCKER_NAMESPACE/$DOCKER_APP-test tests_e2e

before_deploy:
  - echo $DOCKERHUB_PWD | docker login --username $DOCKER_NAMESPACE --password-stdin
  - docker push $DOCKER_NAMESPACE/$DOCKER_APP:$TRAVIS_COMMIT
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker push $DOCKER_NAMESPACE/$DOCKER_APP; fi

deploy:
  - provider: script
    script: 
      echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com &&
      docker tag $DOCKER_NAMESPACE/$DOCKER_APP:$TRAVIS_COMMIT registry.heroku.com/$HEROKU_APP/web &&
      docker push registry.heroku.com/$HEROKU_APP/web &&
      wget -qO- https://cli-assets.heroku.com/install.sh | sh &&
      /usr/local/bin/heroku container:release --app dev-ops-todo-app web
    on:
      branch: module-11

branches:
  only:
  - module-11
    
notifications:
  email:
    recipients:
    - pcoulson@btinternet.com
    on_success: change
    on_failure: always
